from fastapi import FastAPI
from .middleware import custom_logging_middleware
import time

app = FastAPI(title="Logging Middleware Example")

# Register our custom middleware with the application
app.middleware("http")(custom_logging_middleware)

@app.get("/")
def read_root():
    return {"message": "Hello! Check your terminal to see the log generated by the middleware."}

@app.get("/slow-task")
def read_slow_task():
    time.sleep(1.5)  # Simulate a slow task
    return {"message": "This task took 1.5 seconds. Check the log time!"}
